In [1]:
import yfinance as yf
from datetime import date
import pandas as pd

In [2]:
end = date.today()
tickers_list = ["TSLA","GM","F","DODGX"]


data = pd.DataFrame(columns=tickers_list)

for ticker in tickers_list:
    data[ticker] = yf.download(ticker, "2016-2-22", end)["Adj Close"]

df = data.reset_index()

df.to_csv("yfinance.csv", index=False)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [3]:
data

                  TSLA         GM          F       DODGX
Date
2016-02-22  177.740005  24.753447  10.040338  108.349815
2016-02-23  177.210007  24.544594   9.928422  106.539925
2016-02-24  179.000000  24.093464   9.656631  107.033508
2016-02-25  187.429993  24.644842   9.904439  108.113754
2016-02-26  190.339996  24.753447   9.968390  108.779030
...                ...        ...        ...         ...
2020-02-06  748.960022  34.330002   8.250000  195.660004
2020-02-07  748.070007  33.630001   8.110000  194.720001
2020-02-10  771.280029  34.250000   8.060000  195.300003
2020-02-11  774.380005  35.009998   8.100000  196.860001
2020-02-12  767.289978  35.490002   8.240000  198.570007

[1002 rows x 4 columns]